qtest.url=
qtest.api.token=
qtest.project.id=
qtest.release.cycle.id=
qtest.enabled=false
qtest.attach.screenshots=true
qtest.cert.path=./src/test/resources/qtest.jks
qtest.cert.password=changeit