package com.nosuchelements.dsa.dataobjects;

import java.util.Map;

import org.springframework.stereotype.Component;

import lombok.Data;

@Component
@Data
public class ADM_DTO  {

	
	private String screenset;
	private String appNumber;
	private String strategy;
	private String prodType;
	private String dateReceived;
	private String microfilm;
	private String drlicPhoto;
	private String idType;
	private String serialNumber;
	private String issued;
	private String gender;
	private String name;
	private String idExpDate;
	private String embossingName;
	private String dateVerified;
	private String homePhone;
	private String cellPhone;
	private String mgmtStoreVerified;
	private String dob;
	private String addr1;
	private String addr2;
	private String city;
	private String province;
	private String postalCode;
	private String country;
	private String yearsAtAddr;
	private String monthsAtAddr;
	private String hometype;
	private String language;
	private String email;
	private String loyaltyNumber;
	private String loyaltyID;
	private String prevAddr1;
	private String prevAddr2;
	private String prevCity;
	private String prevProvince;
	private String prevPostalCode;
	private String prevCountry;
	private String visaMmAmex;
	private String bankLoan;
	private String cheqAcct;
	private String savAcct;
	private String storeCard;
	private String oilGasCard;
	private String employeeNumber;
	private String empStatus;
	private String occupationDesc;
	private String occupationCat;
	private String jobCatV2;
	private String employer;
	private String empCity;
	private String empProv;
	private String empCountry;
	private String empPhone;
	private String password;
	private String yearsAtEmp;
	private String monthsAtEmp;
	private String busPhone;
	private String grossAnnualIncome;
	private String incomeFreq;
	private String reqCreditLimit;
	private String rentMort;
	private String sin;
	private String householdAnnualIncome;
	private String apInvest;
	private String amlFix;
	private String potentialFrd;
	private String addCardName;
	private String addCardEmbName;
	private String addCardRelationship;
	private String addCardDOB;
	private String addCardSuppPhone;
	private String sameAddr;
	private String numCards;
	private String suppAddr1;
	private String suppAddr2;
	private String suppCity;
	private String suppProvince;
	private String suppPostalCode;
	private String suppCountry;
	private String suppAddrDesc;
	private String appSigned;
	private String dateSigned;
	private String signatureMatched;
	private String applAgreedToTerms;
	private String insType;
	private String appSignedIns;
	private String insAgreed;
	private String tableSerialNumber;
	private String StoreNUmber;
	private String agentID;
	private String channel;
	private String eStmt;
	private String asc;
	private String promo;
	private String newPan;
	private String queue;
	private String status;
	private String invalidAddr;
	private String prsnInHshold;
	private String lm;
	private String pswd;
	private String kofaxConsent;
	private String secureKeyConsent;
	private String secureKeyConsDt;
	private String SKEKYCFlag;
	private String SKEBVSID;
	
	
	private String resultCode;
	private String resultMsg;
	private String dsaTrtmnt;
	
	public String handleNulls(String val) throws Exception {
		return val == null ? "" : val.trim();
	}
	
	public void setAdmDto(Map<String, String> aDMmap) {
		try {
			
		screenset = handleNulls(aDMmap.get("Screenset"));
		appNumber = handleNulls(aDMmap.get("AppNumber"));
		strategy= handleNulls(aDMmap.get("Strategy"));
		prodType= handleNulls(aDMmap.get("ProdType"));
		dateReceived= handleNulls(aDMmap.get("DateReceived"));
		microfilm= handleNulls(aDMmap.get("Microfilm"));
		drlicPhoto= handleNulls(aDMmap.get("DrlicPhoto"));
		idType= handleNulls(aDMmap.get("IdType"));
		serialNumber= handleNulls(aDMmap.get("SerialNumber"));
		issued= handleNulls(aDMmap.get("Issued"));
		gender= handleNulls(aDMmap.get("Gender"));
		name= handleNulls(aDMmap.get("Name"));
		idExpDate= handleNulls(aDMmap.get("IdExpDate"));
		embossingName= handleNulls(aDMmap.get("EmbossingName"));
		dateVerified= handleNulls(aDMmap.get("DateVerified"));
		homePhone= handleNulls(aDMmap.get("HomePhone"));
		cellPhone= handleNulls(aDMmap.get("CellPhone"));
		mgmtStoreVerified= handleNulls(aDMmap.get("MgmtStoreVerified"));
		dob= handleNulls(aDMmap.get("Dob"));
		addr1= handleNulls(aDMmap.get("Addr1"));
		addr2= handleNulls(aDMmap.get("Addr2"));
		city= handleNulls(aDMmap.get("City"));
		province= handleNulls(aDMmap.get("Province"));
		postalCode= handleNulls(aDMmap.get("PostalCode"));
		country= handleNulls(aDMmap.get("Country"));
		yearsAtAddr= handleNulls(aDMmap.get("YearsAtAddr"));
		monthsAtAddr= handleNulls(aDMmap.get("MonthsAtAddr"));
		hometype= handleNulls(aDMmap.get("Hometype"));
		language= handleNulls(aDMmap.get("Language"));
		email= handleNulls(aDMmap.get("Email"));
		loyaltyNumber= handleNulls(aDMmap.get("LoyaltyNumber"));
		loyaltyID= handleNulls(aDMmap.get("LoyaltyID"));
		prevAddr1= handleNulls(aDMmap.get("PrevAddr1"));
		prevAddr2= handleNulls(aDMmap.get("PrevAddr2"));
		prevCity= handleNulls(aDMmap.get("PrevCity"));
		prevProvince= handleNulls(aDMmap.get("PrevProvince"));
		prevPostalCode= handleNulls(aDMmap.get("PrevPostalCode"));
		prevCountry= handleNulls(aDMmap.get("PrevCountry"));
		visaMmAmex= handleNulls(aDMmap.get("VisaMmAmex"));
		bankLoan= handleNulls(aDMmap.get("BankLoan"));
		cheqAcct= handleNulls(aDMmap.get("CheqAcct"));
		savAcct= handleNulls(aDMmap.get("SavAcct"));
		storeCard= handleNulls(aDMmap.get("StoreCard"));
		oilGasCard= handleNulls(aDMmap.get("OilGasCard"));
		employeeNumber= handleNulls(aDMmap.get("EmployeeNumber"));
		empStatus= handleNulls(aDMmap.get("EmpStatus"));
		occupationDesc= handleNulls(aDMmap.get("OccupationDesc"));
		occupationCat= handleNulls(aDMmap.get("OccupationCat"));
		jobCatV2= handleNulls(aDMmap.get("JobCatV2"));
		employer= handleNulls(aDMmap.get("Employer"));
		empCity= handleNulls(aDMmap.get("EmpCity"));
		empProv= handleNulls(aDMmap.get("EmpProv"));
		empCountry= handleNulls(aDMmap.get("EmpCountry"));
		empPhone= handleNulls(aDMmap.get("EmpPhone"));
		password= handleNulls(aDMmap.get("Password"));
		yearsAtEmp= handleNulls(aDMmap.get("YearsAtEmp"));
		monthsAtEmp= handleNulls(aDMmap.get("MonthsAtEmp"));
		busPhone= handleNulls(aDMmap.get("BusPhone"));
		grossAnnualIncome= handleNulls(aDMmap.get("GrossAnnualIncome"));
		incomeFreq= handleNulls(aDMmap.get("IncomeFreq"));
		reqCreditLimit= handleNulls(aDMmap.get("ReqCredLmt"));
		rentMort= handleNulls(aDMmap.get("RentMort"));
		sin= handleNulls(aDMmap.get("Sin"));
		householdAnnualIncome= handleNulls(aDMmap.get("HouseholdAnnualIncome"));
		apInvest= handleNulls(aDMmap.get("ApInvest"));
		amlFix= handleNulls(aDMmap.get("AmlFix"));
		potentialFrd= handleNulls(aDMmap.get("PotentialFrd"));
		eStmt = handleNulls(aDMmap.get("eStmt"));
		addCardName= handleNulls(aDMmap.get("AddCardName"));
		addCardEmbName= handleNulls(aDMmap.get("AddCardEmbName"));
		addCardRelationship= handleNulls(aDMmap.get("AddCardRelationship"));
		addCardDOB= handleNulls(aDMmap.get("AddCardDOB"));
			  addCardSuppPhone= handleNulls(aDMmap.get("AddCardSuppPhone"));
			  sameAddr= handleNulls(aDMmap.get("SameAddr"));
			  numCards= handleNulls(aDMmap.get("NumCards"));
			  suppAddr1= handleNulls(aDMmap.get("SuppAddr1"));
			  suppAddr2= handleNulls(aDMmap.get("SuppAddr2"));
			  suppCity= handleNulls(aDMmap.get("SuppCity"));
			  suppProvince= handleNulls(aDMmap.get("SuppProvince"));
			  suppPostalCode= handleNulls(aDMmap.get("SuppPostalCode"));
			  suppCountry= handleNulls(aDMmap.get("SuppCountry"));
			  suppAddrDesc= handleNulls(aDMmap.get("SuppAddrDesc"));
			  appSigned= handleNulls(aDMmap.get("AppSigned"));
			  dateSigned= handleNulls(aDMmap.get("DateSigned"));
			  signatureMatched= handleNulls(aDMmap.get("SignatureMatched"));
			  applAgreedToTerms= handleNulls(aDMmap.get("ApplAgreedToTerms"));
			  insType= handleNulls(aDMmap.get("InsType"));
			  appSignedIns= handleNulls(aDMmap.get("AppSignedIns"));
			  insAgreed= handleNulls(aDMmap.get("InsAgreed"));
			  tableSerialNumber= handleNulls(aDMmap.get("TableSerialNumber"));
			  StoreNUmber= handleNulls(aDMmap.get("StoreNUmber"));
			  agentID= handleNulls(aDMmap.get("AgentID"));
			  channel= handleNulls(aDMmap.get("Channel"));
			  asc= handleNulls(aDMmap.get("Asc"));
			  promo= handleNulls(aDMmap.get("Promo"));
			  newPan= handleNulls(aDMmap.get("NewPan"));
			  queue= handleNulls(aDMmap.get("Queue"));
			  status= handleNulls(aDMmap.get("Status"));
			  invalidAddr= handleNulls(aDMmap.get("InvalidAddr"));
			  prsnInHshold= handleNulls(aDMmap.get("PrsnInHshold"));
			  lm= handleNulls(aDMmap.get("Lm"));
			  pswd= handleNulls(aDMmap.get("Pswd"));
			  kofaxConsent= handleNulls(aDMmap.get("KofaxConsent"));
			  secureKeyConsent= handleNulls(aDMmap.get("SecureKeyConsent"));
			  secureKeyConsDt= handleNulls(aDMmap.get("SecureKeyConsDt"));
			SKEKYCFlag= handleNulls(aDMmap.get("SKEKYCFlag"));
			SKEBVSID= handleNulls(aDMmap.get("SKEBVSID"));
			resultCode= handleNulls(aDMmap.get("ResultCode"));
			resultMsg= handleNulls(aDMmap.get("ResultMsg"));
			 dsaTrtmnt= handleNulls(aDMmap.get("DsaTrtmnt"));
		}catch(Exception e) {
			e.printStackTrace();
		}
		
	}
}
